{ config, lib, ... }:
{
  wayland.windowManager.hyprland =
    let
      lua = lib.generators.mkLuaInline;
      luaTable = table: (lua (lib.generators.toLua { } table));

      env = key: value: {
        _args = [
          "${(toString key)}"
          "${(toString value)}"
        ];
      };
      bind = key: action: {
        _args = [
          key
          (lua action)
        ];
      };
      bindo = key: action: opts: {
        _args = [
          key
          (lua action)
          (luaTable opts)
        ];
      };
      on = id: action: {
        _args = [
          id
          (lua "function() ${action} end")
        ];
      };
      on_arg = id: action: {
        _args = [
          id
          (lua ''
            function(...)
              local arg = {...}
              ${action}
            end
          '')
        ];
      };
      monitor = opts: {
        _args = [
          (luaTable opts)
        ];
      };
      workspace_rule = opts: {
        _args = [
          (luaTable opts)
        ];
      };
      animation = opts: {
        _args = [
          (luaTable opts)
        ];
      };
      window_rule = opts: {
        _args = [
          (luaTable opts)
        ];
      };

      # Dispatchers
      exec = cmd: ''hl.dsp.exec_cmd("${cmd}")'';
      layout = msg: ''hl.dsp.layout("${msg}")'';
      window_float_toggle = "hl.dsp.window.float({action=toggle})";
      window_close = "hl.dsp.window.close()";
      window_drag = "hl.dsp.window.drag()";
      window_resize = "hl.dsp.window.resize()";

      window_toggle_special = ''
        function()
          local current_is_special = hl.get_active_special_workspace() ~= nil
          local workspace_id = hl.get_active_workspace().id

          if current_is_special then
            hl.dispatch(hl.dsp.window.move({workspace=workspace_id}))
          else
            hl.dispatch(hl.dsp.window.move({workspace="special:special"}))
          end
        end
      '';
      workspace_toggle_special = "hl.dsp.workspace.toggle_special(\"special\")";

      _cycle_dsp = scrolling_cmd: monocle_cmd: ''
        function()
          local workspace = hl.get_active_special_workspace() or
                            hl.get_active_workspace()

          local layout = workspace.tiled_layout
          if layout == "scrolling" then
            hl.dispatch(hl.dsp.layout("${scrolling_cmd}"))
          elseif layout == "monocle" then
            hl.dispatch(hl.dsp.layout("${monocle_cmd}"))
          end
        end
      '';
      cycle_window_prev = _cycle_dsp "focus l" "cycleprev";
      cycle_window_next = _cycle_dsp "focus r" "cyclenext";
      # cycle_window_prev = _cycle_dsp {
      #   scrolling = lua (layout "focus l");
      #   monocle = lua (layout "cycleprev");
      # };
      # cycle_window_next = _cycle_dsp {
      #   scrolling = lua (layout "focus r");
      #   monocle = lua (layout "cyclenext");
      # };

      # Immediate
      iexec = cmd: ''hl.exec_cmd("${cmd}")'';
    in
    {
      enable = true;
      systemd.enable = false;

      settings = {
        config = {
          autogenerated = false;

          general = {
            gaps_in = 1;
            gaps_out = 2;
            border_size = 1;
          };

          decoration = {
            rounding = 5;
          };

          input = {
            kb_options = "caps:swapescape";

            touchpad = {
              natural_scroll = true;
            };
          };

          scrolling = {
            fullscreen_on_one_column = true;
            column_width = 0.5;
            focus_fit_method = 1;
            follow_focus = true;
            follow_min_visible = 0.4;
            explicit_column_widths = "0.333,0.5,0.667,1.0";
            wrap_focus = true;
            wrap_swapcol = true;
            direction = "right";
          };

          xwayland = {
            force_zero_scaling = true;
          };
        };

        env = [
          (env "HYPRCURSOR_SIZE" config.stylix.cursor.size)
          (env "XCURSOR_SIZE" config.stylix.cursor.size)
        ];

        bind = [
          # System shortcuts
          (bindo "SUPER + L" (exec "loginctl lock-session") {
            locked = true;
          })
          (bindo "SUPER + SHIFT + L" (exec "loginctl lock-session") {
            locked = true;
          })
          (bind "SUPER + space" (exec "rofi -show drun"))

          # Window manipulation
          (bindo "SUPER + SHIFT + grave" window_toggle_special { locked = true; })
          (bindo "SUPER + F" window_float_toggle { locked = true; })
          (bindo "SUPER + Q" window_close { locked = true; })
          (bindo "SUPER + mouse:272" window_drag { locked = true; })
          (bindo "SUPER + SHIFT + mouse:272" window_resize { locked = true; })
          (bindo "SUPER + equal" (layout "colresize +conf") { locked = true; })
          (bindo "SUPER + minus" (layout "colresize -conf") { locked = true; })

          # Workspace navigation
          (bindo "SUPER + grave" workspace_toggle_special { locked = true; })

          (bindo "SUPER + bracketleft" cycle_window_prev { locked = true; })
          (bindo "SUPER + bracketright" cycle_window_next { locked = true; })

          (bindo "SUPER + SHIFT + bracketleft" (layout "swapcol l") { locked = true; })
          (bindo "SUPER + SHIFT + bracketright" (layout "swapcol r") { locked = true; })

          # Program shortcuts
          (bind "SUPER + RETURN" (exec "ghostty --gtk-single-instance=true"))
          (bind "SUPER + B" (exec "zen-beta"))

          # Media keys
          (bindo "XF86AudioMute" (exec "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && eww poll volume") {
            locked = true;
          })
          (bindo "XF86AudioLowerVolume" (exec "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && eww poll volume")
            { locked = true; }
          )
          (bindo "XF86AudioRaiseVolume" (exec "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && eww poll volume")
            { locked = true; }
          )
          (bindo "XF86AudioMicMute" (exec "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle") { locked = true; })
          (bindo "XF86MonBrightnessDown" (exec "brightnessctl s 10%- && eww poll brightness") {
            locked = true;
          })
          (bindo "XF86MonBrightnessUp" (exec "brightnessctl s 10%+ && eww poll brightness") {
            locked = true;
          })
          (bindo "XF86Calculator" (exec "ghostty +new-window -e euporie --edit-mode vi notebook") {
            locked = true;
          })

          # Screenshots
          (bind "SUPER + S" (exec "hyprshot -m active -m window"))
          (bind "SUPER + SHIFT + S" (exec "hyprshot -z -m region"))
        ];

        on = [
          # Cheap workaround for hyprpaper & hypridle not starting automatically
          (on "hyprland.start" (iexec "systemctl --user start hyprpaper && systemctl --user start hypridle"))

          (on "hyprland.start" (iexec "hyprlock || hyprctl dispatch 'uwsm stop'"))
          (on "hyprland.start" (
            iexec "ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false"
          ))
          (on "hyprland.start" (iexec "eww open sidebar"))

          (on_arg "window.active" ''
            if type(arg[1].initial_title) == "string" and arg[1].initial_title:sub(1,9) == "Minecraft" then
              hl.config({input={kb_options=""}})
            else
              hl.config({input={kb_options="caps:swapescape"}})
            end
          '')
        ];

        monitor = [
          # 14are05 display
          (monitor {
            output = "desc:LG Display 0x40A9";
            mode = "1920x1080@59.98";
            position = "auto";
            scale = 1.25;
          })

          # Undeclared monitors use default behaviour
          (monitor {
            output = "";
            mode = "preferred";
            position = "auto";
            scale = "auto";
          })
        ];

        workspace_rule = [
          # The one true workspace :tm:
          (workspace_rule {
            workspace = "1";
            monitor = "";
            default = true;
            layout = "scrolling";
            gaps_out = {
              left = 40;
            };
          })

          (workspace_rule {
            workspace = "special:special";
            monitor = "";
            layout = "monocle";
            gaps_out = {
              left = 40;
            };
          })
        ];

        animation = [
          (animation {
            leaf = "global";
            enabled = false;
          })
          (animation {
            leaf = "windows";
            enabled = false;
          })
          (animation {
            leaf = "windowsIn";
            enabled = false;
          })
          (animation {
            leaf = "windowsOut";
            enabled = false;
          })
          (animation {
            leaf = "windowsMove";
            enabled = false;
          })
          (animation {
            leaf = "layers";
            enabled = false;
          })
          (animation {
            leaf = "layersIn";
            enabled = false;
          })
          (animation {
            leaf = "layersOut";
            enabled = false;
          })
          (animation {
            leaf = "fade";
            enabled = false;
          })
          (animation {
            leaf = "fadeIn";
            enabled = false;
          })
          (animation {
            leaf = "fadeOut";
            enabled = false;
          })
          (animation {
            leaf = "fadeSwitch";
            enabled = false;
          })
          (animation {
            leaf = "fadeShadow";
            enabled = false;
          })
          (animation {
            leaf = "fadeGlow";
            enabled = false;
          })
          (animation {
            leaf = "fadeDim";
            enabled = false;
          })
          (animation {
            leaf = "fadeLayers";
            enabled = false;
          })
          (animation {
            leaf = "fadeLayersIn";
            enabled = false;
          })
          (animation {
            leaf = "fadeLayersOut";
            enabled = false;
          })
          (animation {
            leaf = "fadePopups";
            enabled = false;
          })
          (animation {
            leaf = "fadePopupsIn";
            enabled = false;
          })
          (animation {
            leaf = "fadePopupsOut";
            enabled = false;
          })
          (animation {
            leaf = "fadeDpms";
            enabled = false;
          })
          (animation {
            leaf = "border";
            enabled = false;
          })
          (animation {
            leaf = "borderangle";
            enabled = false;
          })
          (animation {
            leaf = "shadowangle";
            enabled = false;
          })
          (animation {
            leaf = "glowangle";
            enabled = false;
          })
          (animation {
            leaf = "workspaces";
            enabled = false;
          })
          (animation {
            leaf = "workspacesIn";
            enabled = false;
          })
          (animation {
            leaf = "workspacesOut";
            enabled = false;
          })
          (animation {
            leaf = "specialWorkspace";
            enabled = false;
          })
          (animation {
            leaf = "specialWorkspaceIn";
            enabled = false;
          })
          (animation {
            leaf = "specialWorkspaceOut";
            enabled = false;
          })
          (animation {
            leaf = "zoomFactor";
            enabled = false;
          })
          (animation {
            leaf = "monitorAdded";
            enabled = false;
          })
        ];

        window_rule = [
          (window_rule {
            match = {
              initial_title = "Minecraft*";
            };
            float = true;
            center = true;
          })
        ];
      };
    };

  services.hyprpaper = {
    enable = true;
  };

  programs.hyprshot = {
    enable = true;
    saveLocation = "$HOME/Picture/Screenshots";
  };
}
